title: Deep Vyas . ML Enthusiast and Software Developer

author: Deep Vyas

url: "https://deepvyas.github.io"
baseurl: ""

tracking_id: UA-117922563-1

sass:
        sass_dir: _sass
        style: compressed
